import {
  Navbar,
  AvailEvents,
  FlyerPromote,
  Rekomendasi,
  EventNow,
  Layanan,
  Footer,
} from "@/components";
import Head from "next/head";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link
          href="https://fonts.googleapis.com/css2?family=Work+Sans:ital,wght@0,100..900;1,100..900&display=swap"
          rel="stylesheet"
        />
      </Head>
      <main>
        <div>
          <Navbar />
          <AvailEvents />
          <Rekomendasi />
          <FlyerPromote />
          <EventNow />
          <Layanan />
        </div>
        <Footer />
      </main>
    </div>
  );
}
